# Generated by Django 6.0.3 on 2026-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_project_created_by_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='production_compony',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
