# Generated by Django 6.0.3 on 2026-05-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0004_alter_project_production_compony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crew',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
