# Generated by Django 6.0.3 on 2026-05-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0005_crew_hire_date_crew_phone_delete_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='day_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
