# Generated by Django 6.0.3 on 2026-05-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0006_alter_crew_day_rate_alter_crew_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Films.project'),
        ),
    ]
