# Generated by Django 6.0.3 on 2026-05-12 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0007_alter_expense_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='Films.project'),
        ),
    ]
