# Generated by Django 6.0.3 on 2026-05-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0008_alter_crew_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_film', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_assignments', to='Films.crew')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Films.project')),
            ],
            options={
                'unique_together': {('project', 'crew')},
            },
        ),
    ]
